USE [Gabinet dentystyczny];
GO

DROP TABLE IF EXISTS Platnosc;
DROP TABLE IF EXISTS WykonanaUsluga;
DROP TABLE IF EXISTS Rezerwacja;
DROP TABLE IF EXISTS Usluga;
DROP TABLE IF EXISTS Grafik;

DROP TABLE IF EXISTS Gabinet;
DROP TABLE IF EXISTS Dentysta;
DROP TABLE IF EXISTS Recepcjonista;
DROP TABLE IF EXISTS Klient;
DROP TABLE IF EXISTS Osoba;

GO
